### ISSUE TITLE
Respect dark theme

### ISSUE THREAD

**Issue by eveninglily** [bitcamp/alum#1]
![image](https://user-images.githubusercontent.com/2966094/79696688-48e03500-824c-11ea-843b-19bd4a99f860.png)
```
@media (prefers-color-scheme: dark) {

}
```

**Comment by Dorson** [comment]
The CSS rule for **@media screen and (prefers-color-scheme: dark) { }**  would work, but it would enforce one color only, and for the users that have that rule ON already. No way to switch it ON, OFF. Or give it to all as an option. 

To resolve that I did the hard work.

Made and tested code for a CSS color switch with memory. Great for the night and evening time.

See live demo on GitHub page:

https://dorson.github.io/CSS-Dark-Mode-and-color-switch/

Have fun, feel free to fork, copy, adopt, port, etc...

**Comment by eveninglily** [comment]
Closed in https://github.com/bitcamp/alum/commit/40482c15bf15fde6ced1b1ba8544976a00877e7a and follow-ups
